## Cobb County Property Sales Data for January 2024
---
**Initial Exploratory Data Analysis**

In [293]:
# Core
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Datetime handling
from datetime import datetime as dt

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

# Plot styling
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)

---
**Read in Dataset**

In [296]:
file_path = '../01-dataSets/01-sales/Jan24-CobbCountyGA-20260418-7cc55305db214785ab51bb8c78c21dcc.csv'

In [298]:
jan2024 = pd.read_csv(file_path)

---
**Basic Info about Data**

In [301]:
# rows and columns
jan2024.shape

(1465, 18)

In [303]:
# first five rows
jan2024.head(5)

,Parcel ID,Street Name,Owner Name,Owner Address,Grantor,Grantee,Sale Date,Sale Price,Sales Validity,Acres,Tax District,Square Ft,Neighborhood,Zoning,Districts,Landlots,Foundation,School District
0,19004500540,2364 ELLIS MOUNTAIN DR SW,KENNETH GEORGE BEREZINSKI REVOCABLE TRUS | C/O...,KENNETH GEORGE BEREZINSKI REVOCABLE TRUS | C/O...,CND ELLIS LLC,WEEKLEY HOMES LLC,1/31/2024,"$1,463,000.00",NaN,0.67,(9) UNINCORPORATED,3201,ELLIS - 19034527,NaN,19,45,1 - NONE,Hillgrove High - 520
1,17041600350,768 TIMBERLAND ST,EVERHART CLAYTON & PLATT KIMBERLY,EVERHART CLAYTON & PLATT KIMBERLY | 768 TIMBE...,CHAPMAN ERIC & CAPPARELLI TANIA,HABERSTROH BRADLEY & AMANDA,1/31/2024,"$475,000.00",VALID SALE,0.23,(6) SMYRNA,1125,CHENEY WOODS - 06170072,NaN,17,416,4 - FULL,Campbell High - 517
2,20030200460,492 TEAGUE DR,DUPLANTIS ZACHARY NATHANIEL,DUPLANTIS ZACHARY NATHANIEL | 492 TEAGUE DR N...,ONLINE ABSTRACTING LLC,AJS AUCTIONS LLC,1/8/2024,"$170,000.00",VALID SALE,0.00,(9) UNINCORPORATED,1480,RED ROCK HILLS - 20051497,NaN,20,302,4 - FULL,Harrison High - 516
3,17070100420,2018 NANCY CIR,NICOLAUS CHRISTOPHER & THOMAS SUMMER,NICOLAUS CHRISTOPHER & THOMAS SUMMER | 2018 N...,HARTSELL ANN WILSON,CMNC HOMES LLC,1/16/2024,"$225,000.00",NaN,0.00,(6) SMYRNA,1845,ARGYLE ESTATES I - 17072820,NaN,17,701,2 - CRAWL,Campbell High - 517
4,20018701940,5327 CAMDEN LAKE DR,LILA DILCIA M,LILA DILCIA M | 5327 CAMDEN LAKE DR NW | ACWO...,LILA DILCIA MARIA,LILA BIANCA M,1/4/2024,$0.00,NaN,0.00,(9) UNINCORPORATED,2967,CAMDEN POINTE - 20062972,NaN,20,187,4 - FULL,Allatoona High - 521

In [210]:
# last five rows
jan2024.tail(5)

,Parcel ID,Street Name,Owner Name,Owner Address,Grantor,Grantee,Sale Date,Sale Price,Sales Validity,Acres,Tax District,Square Ft,Neighborhood,Zoning,Districts,Landlots,Foundation,School District
1460,16121601120,99 LAKE ST,DRABIK KIMBERLY ANNETTE,DRABIK KIMBERLY ANNETTE | 3304 GEORGETOWN PL ...,99 LAKE STREET LLC,DRABIK KIMBERLY ANNETTE,1/2/2024,"$370,000.00",VALID SALE,0.00,(4) MARIETTA,988,CITY OF MARIETTA - 04034015,NaN,16,1216,2 - CRAWL,Marietta High - 999
1461,16029600120,210 SUBURBAN DR,TOZZO RENALDO & GOULART CARLOS A,TOZZO RENALDO & GOULART CARLOS A | 210 SUBURB...,HICKS CLIFFORD BLAKE,TOZZO RENALDO & GOULART CARLOS A,1/2/2024,"$310,000.00",VALID SALE,0.00,(9) UNINCORPORATED,1515,DURHAM ESTATES - 16121176,NaN,16,296,3 - PART,Sprayberry High - 510
1462,16027100200,1782 JODY DR,MIS LLC,MIS LLC | 1095 OLD ROSWELL RD | ROSWELL GA 30076,SAYAG YIZHAQ,MIS LLC,1/1/2024,$0.00,NaN,0.00,(9) UNINCORPORATED,1480,SHALLOWFORD OAKS - 16111742,NaN,16,271,1 - NONE,Kell High - 519
1463,19067600280,4956 SHIPP RD,CENTENO LUIS A & | VAZQUEZ GUADALUPE ALEJANDRA...,CENTENO LUIS A & | VAZQUEZ GUADALUPE ALEJANDRA...,GOUCIDE YACINTHE & SILVIA,CENTENO LUIS A &,1/1/2024,$0.00,NaN,0.00,(5) POWDER SPRINGS,1663,COUNTRY COVE - 19052629,NaN,19,676,4 - FULL,McEachern High - 501
1464,16042700790,120 CHASTAIN RD UNIT 604,SOUTHERN MAGNOLIA ENDEAVORS LLC,SOUTHERN MAGNOLIA ENDEAVORS LLC | 3460 PRESTO...,THOMPSON THOMAS B,SOUTHERN MAGNOLIA ENDEAVORS LLC,1/1/2024,$10.00,NaN,0.00,(9) UNINCORPORATED,1614,BROOKHAVEN OF EAST COBB - CONDOS - 20019540,NaN,16,427,1 - NONE,Kell High - 519

---
**Information about Columns: data types, null values, standardize names**

In [305]:
# initial column data types
jan2024.dtypes

Parcel ID            int64
Street Name         object
Owner Name          object
Owner Address       object
Grantor             object
Grantee             object
Sale Date           object
Sale Price          object
Sales Validity      object
Acres              float64
Tax District        object
Square Ft            int64
Neighborhood        object
Zoning              object
Districts            int64
Landlots             int64
Foundation          object
School District     object
dtype: object

In [307]:
# snake_case column names
jan2024.columns = jan2024.columns.str.lower()
jan2024.columns = jan2024.columns.str.strip().str.replace(' ', '_')

# display new column names
jan2024.columns

Index(['parcel_id', 'street_name', 'owner_name', 'owner_address', 'grantor',
       'grantee', 'sale_date', 'sale_price', 'sales_validity', 'acres',
       'tax_district', 'square_ft', 'neighborhood', 'zoning', 'districts',
       'landlots', 'foundation', 'school_district'],
      dtype='object')

In [309]:
# check null values
jan2024.isnull().sum()

parcel_id             0
street_name           0
owner_name            0
owner_address         0
grantor               0
grantee               0
sale_date             0
sale_price            0
sales_validity      916
acres                 0
tax_district          0
square_ft             0
neighborhood          0
zoning             1318
districts             0
landlots              0
foundation           87
school_district      33
dtype: int64

---
**Review Columns Unique Values and Counts**

Turn this into a function to avoid DRY: pass in the column names directly from DF

In [312]:
# unique values and count for parcel_id
print(jan2024['parcel_id'].nunique())
jan2024['parcel_id'].value_counts()

1307

parcel_id
20010400450    5
17070300470    5
20016603390    5
18007700510    4
17013800030    3
              ..
20007800300    1
20023300590    1
16084800820    1
16063200100    1
16042700790    1
Name: count, Length: 1307, dtype: int64

In [314]:
# unique values and count for street_name
print(jan2024['street_name'].nunique())
jan2024['street_name'].value_counts()

1303

street_name
2256 LAKEWOOD DR NW         5
2021 GLENROY PL             5
3580 NOWLIN RD              5
506 GRESHAM RD SW           4
680 POWDER SPRINGS ST       3
                           ..
4286 PINEVIEW DR SW         1
5993 BAYSIDE DR             1
5360 THORNAPPLE LN          1
1535 ROXBURY PL             1
120 CHASTAIN RD UNIT 604    1
Name: count, Length: 1303, dtype: int64

In [316]:
# unique values and count for owner_name
print(jan2024['owner_name'].nunique())
jan2024['owner_name'].value_counts()

1253

owner_name
GA WEST OAK TRACE LLC                      16
DGS RESIDENTIAL PROPERTIES LLC              8
SELAM WELDE LIVING TRUST                    6
MOSTON CHAD                                 5
RUDDER ETHAN & MARQUES NORA NORMAN          5
                                           ..
BROWN DIRK JAMES & RAWLS LAURIE NICOLE      1
KINOSHITA HIROKAZU                          1
WOODWARD JAMES ANDREW & LINDSAY             1
BELL PATRICK WHITTEMORE & AMBER ARNETTE     1
SOUTHERN MAGNOLIA ENDEAVORS LLC             1
Name: count, Length: 1253, dtype: int64

In [318]:
# unique values and count for owner_address
print(jan2024['owner_address'].nunique())
jan2024['owner_address'].value_counts()

1260

owner_address
GA WEST OAK TRACE LLC | 8605  SANTA MONICA BLVD | WEST HOLLYWOOD CA 90069               16
PLAZA TALPA MARIETTA LLC | 1564  MCCURDY DR | STONE MOUNTAIN GA 30083                    5
DGS RESIDENTIAL PROPERTIES LLC | 1263  ROSWELL RD | MARIETTA GA 30062                    5
WILLIAMS DENVER L & HOPKINS BRIANA M | 2021  GLENROY PL SE | SMYRNA GA 30080             5
MOSTON CHAD | 2256  LAKEWOOD DR NW | KENNESAW GA 30152                                   5
                                                                                        ..
BROWN DIRK JAMES & RAWLS LAURIE NICOLE | 4286  PINEVIEW DR | POWDER SPRINGS GA 30127     1
KINOSHITA HIROKAZU | 5050  QUORUM DR | DALLAS TX 75254                                   1
WOODWARD JAMES ANDREW & LINDSAY | 2360  THORNAPPLE LN NW | ACWORTH GA 30101              1
BELL PATRICK WHITTEMORE & AMBER ARNETTE | 1535  ROXBURY PL | MARIETTA GA 30062           1
SOUTHERN MAGNOLIA ENDEAVORS LLC | 3460  PRESTON RIDGE RD | ALPHARETTA GA 30005           1
Name: count, Length: 1260, dtype: int64

In [320]:
# unique values and count for grantor
print(jan2024['grantor'].nunique())
jan2024['grantor'].value_counts()

1279

grantor
TRATON LLC                                 23
OPENDOOR PROPERTY TRUST I                  15
OPEN HOUSE ATLANTA REALTY & INVESTMENTS    10
CND ELLIS LLC                               7
KERLEY FAMILY HOMES LLC                     7
                                           ..
BARNARD SHANNYN                             1
HAU SHANNON                                 1
HUTTO W HARRIS & JEANNE W                   1
HOSEIN KHALIL                               1
THOMPSON THOMAS B                           1
Name: count, Length: 1279, dtype: int64

In [322]:
# unique values and count for grantee
print(jan2024['grantee'].nunique())
jan2024['grantee'].value_counts()

1304

grantee
OPENDOOR PROPERTY TRUST I          23
TRATON LLC                         19
GA WEST OAK TRACE LLC              10
WEEKLEY HOMES LLC                   7
DGS RESIDENTIAL PROPERTIES LLC      6
                                   ..
HUTCHINGS FAMILY TRUST              1
GILAD ROEI & HESTER LEEZA MAYA      1
WRPV XIV SFR BORROWER LLC           1
PICKETT MICHAEL & MARYANN           1
SOUTHERN MAGNOLIA ENDEAVORS LLC     1
Name: count, Length: 1304, dtype: int64

In [324]:
# unique values and count for sale_date
print(jan2024['sale_date'].nunique())
jan2024['sale_date'].value_counts()

29

sale_date
1/26/2024    126
1/31/2024    118
1/30/2024     93
1/19/2024     89
1/16/2024     80
1/12/2024     73
1/4/2024      71
1/11/2024     71
1/22/2024     63
1/23/2024     62
1/8/2024      61
1/5/2024      60
1/18/2024     59
1/9/2024      59
1/17/2024     57
1/29/2024     53
1/25/2024     51
1/24/2024     50
1/2/2024      47
1/10/2024     46
1/3/2024      43
1/15/2024     11
1/1/2024       5
1/28/2024      5
1/6/2024       3
1/13/2024      3
1/20/2024      3
1/27/2024      2
1/21/2024      1
Name: count, dtype: int64

In [326]:
# unique values and count for sale_price
print(jan2024['sale_price'].nunique())
jan2024['sale_price'].value_counts()

456

sale_price
$0.00            668
$1,329,888.00     10
$550,000.00        9
$700,000.00        9
$250,000.00        9
                ...
$520,000.00        1
$555,000.00        1
$922,921.00        1
$710,000.00        1
$460,925.00        1
Name: count, Length: 456, dtype: int64

In [328]:
# unique values and count for sales_validity
print(jan2024['sales_validity'].nunique())
jan2024['sales_validity'].value_counts()

1

sales_validity
VALID SALE    549
Name: count, dtype: int64

In [330]:
# unique values and count for acres
print(jan2024['acres'].nunique())
jan2024['acres'].value_counts()

239

acres
0.00     1021
0.03       25
0.02       13
0.40        9
0.07        9
         ...
0.02        1
0.13        1
11.98       1
0.47        1
0.27        1
Name: count, Length: 239, dtype: int64

In [331]:
# unique values and count for tax_district
print(jan2024['tax_district'].nunique())
jan2024['tax_district'].value_counts()

11

tax_district
(9) UNINCORPORATED                        911
(M) MABLETON                              141
(4) MARIETTA                              138
(6) SMYRNA                                 89
(5) POWDER SPRINGS                         64
(3) KENNESAW                               59
(1) ACWORTH                                39
(2) AUSTELL                                17
(6   A) SMYRNA TAD 1 ATL RD CORR(2004)      3
(8) TCID                                    2
(9Y) COUNTY CSSD2                           2
Name: count, dtype: int64

In [334]:
# unique values and count for square_ft
print(jan2024['square_ft'].nunique())
jan2024['square_ft'].value_counts()

936

square_ft
0       54
1867    14
1905     9
1080     8
1152     7
        ..
3680     1
2550     1
2968     1
2961     1
1663     1
Name: count, Length: 936, dtype: int64

In [336]:
# unique values and count for neighborhood
print(jan2024['neighborhood'].nunique())
jan2024['neighborhood'].value_counts()

857

neighborhood
HOMESITE - M0009991                            22
WEST OAK TRACE - 19044663                      16
ELLIS - 19034527                                9
HOMESITE - 20049991                             9
THE GATES AT HAMILTON GROVE PH-1 - 04039680     9
                                               ..
SPRING GATE - 19042404                          1
SANDY GLEN - 19033061                           1
CHELSEA TRACE - 19032655                        1
ALEXANDER H F - M0000943                        1
COUNTRY COVE - 19052629                         1
Name: count, Length: 857, dtype: int64

In [338]:
# unique values and count for zoning
print(jan2024['zoning'].nunique())
jan2024['zoning'].value_counts()

26

zoning
R-20 - SINGLE FAM RES 20,000 SF             20
R-3 - SINGLE FAMILY RES                     19
R-30 - SINGLE FAM RES 30,000 SF             15
CRC - COMMUNITY RETAIL COMMERCIAL           10
FST - FEE SIMPLE TOWNHOUSE RES              10
R-4 - SINGLE FAMILY RESIDENTIAL              9
LI - LIGHT INDUSTRIAL                        8
R-15/OSC - RES SING FAM/ OPEN SPACE          6
GC - GENERAL COMMERCIAL                      6
OI - OFFICE IND                              5
R-20/R30 - SFR 20,000SF / SFR 30,000SF       5
MU - MIXED USE DEVELOPMENT                   4
RM-8 - RES MULTI FAMILY                      4
R-15/WS - SNGL FAM RES 15,000 SF/ W STIP     4
UC - URBAN CONDO RES                         3
CBD - COMMERCIAL BUSINESS DIST               3
HI - HEAVY INDUSTRIAL                        3
NRC - NBHD RETAIL COMMERCIAL                 3
NS - NEIGHBORHOOD SHOPPING                   2
R15                                          2
PRD MF - PLANNED RES DEV                     1
RM-12 - RES MULTI FAMILY                     1
RSL - RES SENIOR FAM LIVING FACILITI         1
PUD - PLANNED UNIT DEVELOPMENT               1
CS/WS - CONSERVATION SUBD/W STIPULATIO       1
PSC - PLANNED SHOPPING CENTER                1
Name: count, dtype: int64

In [340]:
# unique values and count for districts
print(jan2024['districts'].nunique())
jan2024['districts'].value_counts()

6

districts
16    405
17    343
19    298
20    296
18     75
1      48
Name: count, dtype: int64

In [342]:
# unique values and count for landlots
print(jan2024['landlots'].nunique())
jan2024['landlots'].value_counts()

680

landlots
953     17
104     12
166     10
833      9
1216     9
        ..
1226     1
1        1
1191     1
699      1
427      1
Name: count, Length: 680, dtype: int64

In [344]:
# unique values and count for foundation
print(jan2024['foundation'].nunique())
jan2024['foundation'].value_counts()

4

foundation
4 - FULL     584
1 - NONE     459
2 - CRAWL    222
3 - PART     113
Name: count, dtype: int64

In [346]:
# unique values and count for school_district
print(jan2024['school_district'].nunique())
jan2024['school_district'].value_counts()

17

school_district
Campbell High - 517        167
McEachern High - 501       123
Marietta High - 999        115
Sprayberry High - 510      106
North Cobb High - 505      104
Wheeler High - 509          98
South Cobb High - 503       92
Osborne High - 507          81
Pebblebrook High - 506      71
Allatoona High - 521        68
Walton High - 511           66
Kennesaw Mtn High - 518     64
Hillgrove High - 520        63
Lassiter High - 512         58
Kell High - 519             56
Pope High - 515             55
Harrison High - 516         45
Name: count, dtype: int64

---
**Review Columns: Contents, Stats, Format to Correct Data Type**

Turn this into a function to avoid DRY: pass in the column names directly from DF

In [348]:
# parcel_id has no nulls, convert to strings and confirm
jan2024['parcel_id'] = jan2024['parcel_id'].astype('string')
print(jan2024['parcel_id'].dtype)

string

In [352]:
# verify parcel IDs lengths
jan2024['parcel_id'].str.len().value_counts()

parcel_id
11    1417
10      48
Name: count, dtype: Int64

In [ ]:
# check leading characters for parcel IDs

In [354]:
jan2024['parcel_id'].str[0].value_counts().sort_index()

parcel_id
1    1169
2     296
Name: count, dtype: Int64

In [356]:
# any leading white space in parcel IDs?
jan2024['parcel_id'].str.startswith(' ').sum()

0

In [358]:
# and in case there are any trailing white spaces, remove - then check lengths again for consistency
jan2024['parcel_id'].str.strip().str.len().value_counts()

parcel_id
11    1417
10      48
Name: count, dtype: Int64

In [289]:
# take a look at parcel IDs with 10 characters - first five
jan2024[jan2024['parcel_id'].str.len() == 10]['parcel_id'].head(5)

18    1004700100
41    1022500720
46    1020900100
50    1002800750
69    1022800340
Name: parcel_id, dtype: string

In [291]:
# check the same rows
jan2024[jan2024['parcel_id'].str.len() == 10].head(5)

,parcel_id,street_name,owner_name,owner_address,grantor,grantee,sale_date,sale_price,sales_validity,acres,tax_district,square_ft,neighborhood,zoning,districts,landlots,foundation,school_district
18,1004700100,4655 GILHAMS RD,HENDERSON JUSTIN F & HOMYRA WASSAL,HENDERSON JUSTIN F & HOMYRA WASSAL | 4655 GIL...,LOCKARD DENISE,WALLACE ROBERT & DENISE,1/2/2024,$0.00,NaN,0.00,(9) UNINCORPORATED,3263,PRINCETON COVE - 16032975,NaN,1,47,4 - FULL,Lassiter High - 512
41,1022500720,1392 WATERFORD GREEN DR,BUY LO AND SALE HIGH CONSULTING LLC & | CARTER...,BUY LO AND SALE HIGH CONSULTING LLC & | CARTER...,MINNIE G SEARCY REVOCABLE LIVING TRUST C,LIEMEN FLOORING COMPANY LLC & CARTER AM,1/30/2024,$0.00,NaN,0.00,(9) UNINCORPORATED,4394,WATERFORD GREEN - 16012518,NaN,1,225,4 - FULL,Walton High - 511
46,1020900100,1531 WATERFORD CT,ZACK FRANK A III & FLAUGH CHRISTOPHER C,ZACK FRANK A III & FLAUGH CHRISTOPHER C | 1531...,PAINTER STEVE R & AMANDA DAWN LOWRANCE,OPENDOOR PROPERTY TRUST I,1/4/2024,"$580,400.00",NaN,0.00,(9) UNINCORPORATED,2541,WILLOW POINT - 16011365,NaN,1,209,2 - CRAWL,Walton High - 511
50,1002800750,3444 COLEBROOK TRL NE,CREASY SHARON,CREASY SHARON | 3444 COLEBROOK TRL | ROSWELL ...,GALAXY CHILDERS LAND LLC,BEAM CONSTRUCTION COMPANY INC,1/22/2024,"$250,000.00",VALID SALE,0.50,(9) UNINCORPORATED,3829,GLENCOVE PLACE - 16034667,R15,1,28,1 - NONE,Pope High - 515
69,1022800340,1544 E BANK DR,RIPPEON HARRY ZACHARIAH III & | RIPPEON KAREN ...,RIPPEON HARRY ZACHARIAH III & | RIPPEON KAREN ...,THE ZACK & KAREN RIPPEON REVOCABLE TRUST,RIPPEON HARRY ZACHARIAH III & KAREN DUNS,1/5/2024,$0.00,NaN,0.00,(9) UNINCORPORATED,2864,JACKSONS CREEK - 16011496,NaN,1,228,4 - FULL,Walton High - 511

Nothing odd about the parcel IDs.  Read about Cobb County's parcel ID formatting and conventions, IDs can be anywhere in lenght from 10 to 14.

In [361]:
# street_name also has no nulls, convert to strings and confirm
jan2024['street_name'] = jan2024['street_name'].astype('string')
print(jan2024['street_name'].dtype)

string

In [393]:
# view first 10 entries
jan2024['street_name'].head(10)

0    2364 ELLIS MOUNTAIN DR SW
1            768 TIMBERLAND ST
2                492 TEAGUE DR
3               2018 NANCY CIR
4          5327 CAMDEN LAKE DR
5       4420 OLD STILESBORO RD
6              45 DRISKELL AVE
7           2310 OLD SEWELL RD
8                2612 DREUX CT
9            3005 TREESIDE TER
Name: street_name, dtype: string

In [395]:
# view last 10 entries
jan2024['street_name'].tail(10)

1455                    1125 WINDBROOKE DR
1456                      4155 RIDGE RD SE
1457            3150 WOODWALK DR UNIT 3310
1458    3300 WINDY RIDGE PKWY SE UNIT 1209
1459                 4619 GLORY MAPLE TRCE
1460                            99 LAKE ST
1461                       210 SUBURBAN DR
1462                          1782 JODY DR
1463                         4956 SHIPP RD
1464              120 CHASTAIN RD UNIT 604
Name: street_name, dtype: string

In [397]:
# remove any possible leading/trailing spaces
jan2024['street_name'] = jan2024['street_name'].str.strip()

In [407]:
# sanity check address lengths to catch odd entries
jan2024['street_name'].str.len().describe()

count   1465.00
mean      17.84
std        4.03
min        9.00
25%       15.00
50%       17.00
75%       20.00
max       40.00
Name: street_name, dtype: Float64

My own address is 24 characters long.  IQR shows lengths from 15 thru 20, those addresses should make sense, be correct - not incomplete.

In [416]:
# check addresses with 9 characters
jan2024[jan2024['street_name'].str.len() == 9]['street_name']

38     CHURCH ST
531    WARREN DR
Name: street_name, dtype: string

Numbers are missing.  Check how many addresses are between 9 and 15 characters long.

In [423]:
# view addresses under 15 characters
jan2024[jan2024['street_name'].str.len() < 15]['street_name']

2        492 TEAGUE DR
3       2018 NANCY CIR
8        2612 DREUX CT
13        556 EMBRY LN
14        218 ALDAY LN
             ...
1441      1792 JODY DR
1450     7031 PANDA LN
1460        99 LAKE ST
1462      1782 JODY DR
1463     4956 SHIPP RD
Name: street_name, Length: 256, dtype: string

Nothing odd or out of the ordinary, just keep an eye out for any address where the property number may be missing.

In [418]:
# check addresses with 40 characters
jan2024[jan2024['street_name'].str.len() == 40]['street_name']

1447    1910 CEDAR GLENN WAY BLDG/UNIT 4000/4402
Name: street_name, dtype: string

Looks good.  Move on to the next column.